/* This header file contains two prototypes for saving a trained network, as well as
 * for reading an image from the MNIST database. As the code expands, there may be 
 * added functionality.
 */

#ifndef _FILES_

#define _FILES_
#include "netex.h"
#include <stdbool.h>
#include <gsl/gsl_math.h>

/* get_img grabs data from MNIST CSV files, then returns an array
 * where each pixel is a value 0-1
 * Inputs:
 * 	FILE *fp  | file pointer
 * 	gsl_vect *empty_vect | Vector where read image is going to go
 * Returns nothing.
 */
void get_img(int debug, FILE *fp, gsl_vector *empty_vect);

/* read_net reads in a network settings file generated by main.c
 * and writes it to an empty architecture.
 * Inputs:
 * 	FILE *fp    | file pointer
 * 	layer *lays | Array of layers
 * Returns nothing
 */
void read_net(FILE *fp, layer *lays);

/* get_yaml opens a .yml file and returns the key in a string array
 * which corresponds to the label.
 */
char *get_yaml(char *label, FILE *file);

/*
 * Converts string to boolean
 */
bool strtobool(char *string); 
#endif
